{{- if .Values.nodeport.enabled }}
  {{- $domain := required "A valid DNS domain for the cluster must be provided." .Values.clusterDomain }}
  {{- $clusterName := .Values.clusterName }}
  {{- $fullName := include "cp-kafka.fullname" . }}
  {{- $podFullName := printf "%s-cp-kafka" .Release.Name }}
  {{- $brokers := .Values.brokers | int }}
  {{- $servicePort := .Values.nodeport.servicePort }}
  {{- $annotations := .Values.nodeport.annotations }}
  {{- $root := . }}
  {{- range $i, $e := until $brokers }}
    {{- $externalListenerPort := add $root.Values.nodeport.firstListenerPort $i }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $podFullName) $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" $root }}-{{ $i }}-nodeport
  {{- if $annotations }}
  annotations:
    {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ include "cp-kafka.name" $root }}
    chart: {{ template "cp-kafka.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
spec:
  type: NodePort
  ports:
    - name: external-broker
      targetPort: {{ $servicePort }}
      port: {{ $externalListenerPort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
  selector:
    app: {{ include "cp-kafka.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}
